[package]
name = "rust-math-book-test"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.14"
ndarray-linalg = { version = "0.13.1", features = ["intel-mkl-static"] }
