title: "SATソルバーを実装する"
summary: "数理最適化への応用を念頭にSATソルバーを実装しながらその技術を学ぶ"
topics: ["sat", "数理最適化", "math", "rust"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - introduction
  - boolean_algebra
