title: "Rustで数値計算"
summary: "Rustで数値計算"
topics: ["Rust", "数値計算"]
published: true
allow_override: true
price: 0
chapters:
  - about
  - intro

  # 言語機能
  - language
  - thread
  - simd
  - num_traits

  # 開発技術
  - development
  - versioning
  - criterion
  - flamegraph
  - nom
  - data_format

  # ライブラリ紹介
  - library
  - ndarray_linalg
  - eom
  - fftw
  - rand
  - sfmt
  - rayon
  - plotlib
  - rug
  - mkl

  # 相互運用
  - interop
  - cc
  - pyo3
