name: rust-math-book-test

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  linux:
    runs-on: ubuntu-20.04
    container: ghcr.io/rust-math/rust-mkl:main
    steps:
      - uses: actions/checkout@v1
      - name: Install protoc
        run: apt update && apt install -y protobuf-compiler
      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          command: test
          args: --doc --manifest-path=rust-math-book-test/Cargo.toml

  generate-pdf:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: md-to-pdf
        run: |
          npm install
          node ./books/b4bce1b9ea5e6853cb07/generate_pdf.mjs