name: rust-math-book-test

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          command: test
          args: --doc --manifest-path=rust-math-book-test/Cargo.toml
