name: rust-math-book-test

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  linux:
    runs-on: ubuntu-20.04
    container: ghcr.io/rust-math/intel-mkl-src/mkl-rust:1.49.0
    steps:
      - uses: actions/checkout@v1
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          toolchain: nightly
          command: test
          args: --doc --manifest-path=rust-math-book-test/Cargo.toml
